/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockserial.h"

static const char* CMockString_base = "base";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_data = "data";
static const char* CMockString_dest = "dest";
static const char* CMockString_serial_attach_buffer = "serial_attach_buffer";
static const char* CMockString_serial_close = "serial_close";
static const char* CMockString_serial_open = "serial_open";
static const char* CMockString_serial_read = "serial_read";
static const char* CMockString_serial_write = "serial_write";
static const char* CMockString_size = "size";

typedef struct _CMOCK_serial_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Serial Expected_base;

} CMOCK_serial_open_CALL_INSTANCE;

typedef struct _CMOCK_serial_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Serial Expected_base;

} CMOCK_serial_close_CALL_INSTANCE;

typedef struct _CMOCK_serial_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  Serial Expected_base;
  uint8_t* Expected_dest;

} CMOCK_serial_read_CALL_INSTANCE;

typedef struct _CMOCK_serial_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Serial Expected_base;
  uint8_t* Expected_data;
  uint16_t Expected_size;

} CMOCK_serial_write_CALL_INSTANCE;

typedef struct _CMOCK_serial_attach_buffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Serial Expected_base;
  uint8_t* Expected_buffer;
  uint16_t Expected_size;

} CMOCK_serial_attach_buffer_CALL_INSTANCE;

static struct MockserialInstance
{
  CMOCK_MEM_INDEX_TYPE serial_open_CallInstance;
  CMOCK_MEM_INDEX_TYPE serial_close_CallInstance;
  CMOCK_MEM_INDEX_TYPE serial_read_CallInstance;
  CMOCK_MEM_INDEX_TYPE serial_write_CallInstance;
  CMOCK_MEM_INDEX_TYPE serial_attach_buffer_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockserial_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.serial_open_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_serial_open);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.serial_close_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_serial_close);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.serial_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_serial_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.serial_write_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_serial_write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.serial_attach_buffer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_serial_attach_buffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockserial_Init(void)
{
  Mockserial_Destroy();
}

void Mockserial_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void serial_open(Serial base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_serial_open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_serial_open);
  cmock_call_instance = (CMOCK_serial_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.serial_open_CallInstance);
  Mock.serial_open_CallInstance = CMock_Guts_MemNext(Mock.serial_open_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_serial_open,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(Serial), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_serial_open(CMOCK_serial_open_CALL_INSTANCE* cmock_call_instance, Serial base);
void CMockExpectParameters_serial_open(CMOCK_serial_open_CALL_INSTANCE* cmock_call_instance, Serial base)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(Serial[sizeof(base) == sizeof(Serial) ? 1 : -1])); /* add Serial to :treat_as_array if this causes an error */
}

void serial_open_CMockExpect(UNITY_LINE_TYPE cmock_line, Serial base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_serial_open_CALL_INSTANCE));
  CMOCK_serial_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_serial_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.serial_open_CallInstance = CMock_Guts_MemChain(Mock.serial_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_serial_open(cmock_call_instance, base);
}

void serial_close(Serial base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_serial_close_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_serial_close);
  cmock_call_instance = (CMOCK_serial_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.serial_close_CallInstance);
  Mock.serial_close_CallInstance = CMock_Guts_MemNext(Mock.serial_close_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_serial_close,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(Serial), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_serial_close(CMOCK_serial_close_CALL_INSTANCE* cmock_call_instance, Serial base);
void CMockExpectParameters_serial_close(CMOCK_serial_close_CALL_INSTANCE* cmock_call_instance, Serial base)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(Serial[sizeof(base) == sizeof(Serial) ? 1 : -1])); /* add Serial to :treat_as_array if this causes an error */
}

void serial_close_CMockExpect(UNITY_LINE_TYPE cmock_line, Serial base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_serial_close_CALL_INSTANCE));
  CMOCK_serial_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_serial_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.serial_close_CallInstance = CMock_Guts_MemChain(Mock.serial_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_serial_close(cmock_call_instance, base);
}

uint16_t serial_read(Serial base, uint8_t* dest)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_serial_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_serial_read);
  cmock_call_instance = (CMOCK_serial_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.serial_read_CallInstance);
  Mock.serial_read_CallInstance = CMock_Guts_MemNext(Mock.serial_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_serial_read,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(Serial), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_serial_read,CMockString_dest);
    if (cmock_call_instance->Expected_dest == NULL)
      { UNITY_TEST_ASSERT_NULL(dest, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_dest, dest, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_serial_read(CMOCK_serial_read_CALL_INSTANCE* cmock_call_instance, Serial base, uint8_t* dest);
void CMockExpectParameters_serial_read(CMOCK_serial_read_CALL_INSTANCE* cmock_call_instance, Serial base, uint8_t* dest)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(Serial[sizeof(base) == sizeof(Serial) ? 1 : -1])); /* add Serial to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_dest = dest;
}

void serial_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Serial base, uint8_t* dest, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_serial_read_CALL_INSTANCE));
  CMOCK_serial_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_serial_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.serial_read_CallInstance = CMock_Guts_MemChain(Mock.serial_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_serial_read(cmock_call_instance, base, dest);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void serial_write(Serial base, uint8_t* data, uint16_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_serial_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_serial_write);
  cmock_call_instance = (CMOCK_serial_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.serial_write_CallInstance);
  Mock.serial_write_CallInstance = CMock_Guts_MemNext(Mock.serial_write_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_serial_write,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(Serial), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_serial_write,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_serial_write,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_serial_write(CMOCK_serial_write_CALL_INSTANCE* cmock_call_instance, Serial base, uint8_t* data, uint16_t size);
void CMockExpectParameters_serial_write(CMOCK_serial_write_CALL_INSTANCE* cmock_call_instance, Serial base, uint8_t* data, uint16_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(Serial[sizeof(base) == sizeof(Serial) ? 1 : -1])); /* add Serial to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_size = size;
}

void serial_write_CMockExpect(UNITY_LINE_TYPE cmock_line, Serial base, uint8_t* data, uint16_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_serial_write_CALL_INSTANCE));
  CMOCK_serial_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_serial_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.serial_write_CallInstance = CMock_Guts_MemChain(Mock.serial_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_serial_write(cmock_call_instance, base, data, size);
}

void serial_attach_buffer(Serial base, uint8_t* buffer, uint16_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_serial_attach_buffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_serial_attach_buffer);
  cmock_call_instance = (CMOCK_serial_attach_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.serial_attach_buffer_CallInstance);
  Mock.serial_attach_buffer_CallInstance = CMock_Guts_MemNext(Mock.serial_attach_buffer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_serial_attach_buffer,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(Serial), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_serial_attach_buffer,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_serial_attach_buffer,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_serial_attach_buffer(CMOCK_serial_attach_buffer_CALL_INSTANCE* cmock_call_instance, Serial base, uint8_t* buffer, uint16_t size);
void CMockExpectParameters_serial_attach_buffer(CMOCK_serial_attach_buffer_CALL_INSTANCE* cmock_call_instance, Serial base, uint8_t* buffer, uint16_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(Serial[sizeof(base) == sizeof(Serial) ? 1 : -1])); /* add Serial to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_size = size;
}

void serial_attach_buffer_CMockExpect(UNITY_LINE_TYPE cmock_line, Serial base, uint8_t* buffer, uint16_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_serial_attach_buffer_CALL_INSTANCE));
  CMOCK_serial_attach_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_serial_attach_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.serial_attach_buffer_CallInstance = CMock_Guts_MemChain(Mock.serial_attach_buffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_serial_attach_buffer(cmock_call_instance, base, buffer, size);
}

